server:
  port: 8053
  address: "127.0.0.1"

dns:
  ttl: 300
  enable_recursion: true
  cache_size: 10000

upstream:
  # ControlD DNS-over-HTTPS
  - name: "ControlD DoH Primary"
    address: "dns.controld.com"
    protocol: "https"
    port: 443
    path: "/14a6bhxncz5"
    verify: true

  # ControlD DNS-over-TLS
  - name: "ControlD DoT Primary"
    address: "14a6bhxncz5.dns.controld.com"
    protocol: "tls"
    port: 853
    verify: true

  # Fallback to traditional DNS
  - name: "ControlD Fallback A"
    address: "76.76.2.180"
    protocol: "udp"
    port: 53
    verify: false

  - name: "ControlD Fallback B"
    address: "76.76.10.180"
    protocol: "udp"
    port: 53
    verify: false

log_level: "info"

# Configure the home DNS domain suffix
# Hostnames without a domain will automatically get this suffix
home_dns_domain: "home"

hosts:
  # Simple hostnames - will be resolved as "desktop.home"
  - hostname: "desktop"
    ipv4:
      - "192.168.1.100"

  # Mixed IPv4 + IPv6 - will be resolved as "laptop.home"
  - hostname: "laptop"
    ipv4:
      - "192.168.1.101"
    ipv6:
      - "fe80::1234:5678:90ab:cdef"
      - "2001:db8::1"

  # You can still use fully qualified domain names
  - hostname: "server.local"
    ipv4:
      - "192.168.1.50"

  # Or use different domains
  - hostname: "nas.lab"
    ipv4:
      - "192.168.1.52"

  # Simple hostname - will be resolved as "router.home"
  - hostname: "router"
    ipv4:
      - "192.168.1.1"

  # Simple hostname - will be resolved as "printer.home"
  - hostname: "printer"
    ipv4:
      - "192.168.1.53"

  # Simple hostname - will be resolved as "camera.home"
  - hostname: "camera"
    ipv4:
      - "192.168.1.54"
